---
- hosts: localhost
  gather_facts: no
 
  tasks:
  - name: Ansible check directory.
    stat:
     path: /tmp/testansible
    register: my_folder
 
  - name: "echo if directory already existed"
    debug:
      msg: "the jboss directory is already existed"
    when: my_folder.stat.exists
 
  - name: "Ansible Create directory if not exists"
    file:
     path: /tmp/testansible
     state: directory
     mode: 0755
     group: root
     owner: root
    when: my_folder.stat.exists == false